"""Deterministic section generation from a :class:`SectionPlan`.

Two distinct outputs, matching the spec's outline-only vs. draft-with-
placeholders/validated modes:

- :func:`generate_outline` -- headings, goals, and permitted claim/evidence/
  citation lists. No prose at all.
- :func:`generate_section` -- one neutral template sentence per claim (via
  a :class:`~paperforge.generation.providers.GenerationProvider`), plus a
  visible watermark and inline placeholder markers when the section is
  generated in ``draft_with_placeholders`` mode or contains claims lacking
  sufficient evidence.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any

from paperforge.generation.providers import ClaimContext, GenerationProvider
from paperforge.models.claim import RESULT_EVIDENCE_CLASSES
from paperforge.planning.models import SectionPlan
from paperforge.project_manifest.models import ClaimEntry, ProjectManifest

DRAFT_WATERMARK = (
    "<!-- DRAFT WITH PLACEHOLDERS -- NOT SUBMISSION READY. "
    "Generated by PaperForge's deterministic no-AI generator. -->"
)


@dataclass
class GeneratedSentence:
    claim_id: str
    text: str
    evidence_class: str
    evidence_refs: list[str] = field(default_factory=list)
    citation_keys: list[str] = field(default_factory=list)
    is_placeholder: bool = False
    warnings: list[str] = field(default_factory=list)


@dataclass
class GeneratedSection:
    section: str
    mode: str
    sentences: list[GeneratedSentence] = field(default_factory=list)
    generated_at: str = ""

    def to_markdown(self) -> str:
        lines = []
        if self.mode == "draft_with_placeholders":
            lines.append(DRAFT_WATERMARK)
            lines.append("")
        lines.append(f"## {self.section}")
        lines.append("")
        for s in self.sentences:
            marker = " **[PLACEHOLDER]**" if s.is_placeholder else ""
            lines.append(f"{s.text}{marker}")
            lines.append("")
        if not self.sentences:
            lines.append("_No approved claims are in scope for this section yet._")
            lines.append("")
        return "\n".join(lines)


def _claim_by_id(manifest: ProjectManifest) -> dict[str, ClaimEntry]:
    return {c.id: c for c in manifest.claims}


def generate_outline(plan_section: SectionPlan) -> dict[str, Any]:
    """Structural outline only: headings, goals, permitted claims/evidence/
    citations, unresolved items. Contains zero prose."""

    return {
        "section": plan_section.name,
        "purpose": plan_section.purpose,
        "permitted_claims": list(plan_section.claim_ids),
        "evidence_in_scope": list(plan_section.evidence_refs),
        "citations_in_scope": list(plan_section.citation_keys),
        "figures": list(plan_section.figures),
        "tables": list(plan_section.tables),
    }


def generate_section(
    plan_section: SectionPlan,
    manifest: ProjectManifest,
    *,
    provider: GenerationProvider,
    mode: str = "validated",
    include_placeholders: bool = False,
) -> GeneratedSection:
    """Generate one section's content from its plan using ``provider``.

    ``mode`` is one of ``"validated"`` (default, submission-track) or
    ``"draft_with_placeholders"`` (watermarked, placeholders visible).
    ``include_placeholders``, when true, also renders claims classified
    PLACEHOLDER (normally excluded entirely) with a visible marker --
    only meaningful in ``draft_with_placeholders`` mode.
    """

    claims_by_id = _claim_by_id(manifest)
    sentences: list[GeneratedSentence] = []

    claim_ids = list(plan_section.claim_ids)
    if include_placeholders:
        claim_ids = claim_ids + [
            c.id
            for c in manifest.claims
            if c.evidence_class == "PLACEHOLDER" and c.id not in claim_ids
        ]

    for claim_id in claim_ids:
        claim = claims_by_id.get(claim_id)
        if claim is None:
            continue
        ctx = ClaimContext(
            claim_id=claim.id,
            text=claim.text,
            evidence_class=claim.evidence_class,
            evidence_refs=tuple(claim.evidence_refs),
            citation_keys=tuple(claim.citation_keys),
        )
        text = provider.render_claim_sentence(ctx)
        warnings = []
        is_placeholder = claim.evidence_class == "PLACEHOLDER"
        if claim.evidence_class in RESULT_EVIDENCE_CLASSES and not (
            claim.evidence_refs or claim.citation_keys
        ):
            warnings.append("Result claim has no linked evidence or citation.")
        sentences.append(
            GeneratedSentence(
                claim_id=claim.id,
                text=text,
                evidence_class=claim.evidence_class,
                evidence_refs=list(claim.evidence_refs),
                citation_keys=list(claim.citation_keys),
                is_placeholder=is_placeholder,
                warnings=warnings,
            )
        )

    return GeneratedSection(
        section=plan_section.name,
        mode=mode,
        sentences=sentences,
        generated_at=datetime.now(UTC).isoformat(),
    )


__all__ = [
    "DRAFT_WATERMARK",
    "GeneratedSection",
    "GeneratedSentence",
    "generate_outline",
    "generate_section",
]
